[package]

name = "rwc"
version = "0.3.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]
description = "A wc clone."
license = "AGPL-3.0"
homepage = "https://github.com/steveklabnik/rwc"
repository = "https://github.com/steveklabnik/rwc"

[dependencies]
getopts = "0.2.14"
